spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/pedidosdb
    username: produser
    password: prodpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
